CREATE DATABASE sales_analysis;

USE sales_analysis;
CREATE TABLE sales (
    row_id INT,
    order_id VARCHAR(50),
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(50),
    customer_id VARCHAR(50),
    customer_name VARCHAR(100),
    segment VARCHAR(50),
    country VARCHAR(50),
    city VARCHAR(50),
    state VARCHAR(50),
    postal_code VARCHAR(20),
    region VARCHAR(50),
    product_id VARCHAR(50),
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name VARCHAR(255),
    sales DECIMAL(10,2),
    quantity INT,
    discount DECIMAL(5,2),
    profit DECIMAL(10,2)
);
drop table sales;
CREATE TABLE sales (
    row_id INT,
    order_id VARCHAR(50),
    order_date VARCHAR(20),
    ship_date VARCHAR(20),
    ship_mode VARCHAR(50),
    customer_id VARCHAR(50),
    customer_name VARCHAR(100),
    segment VARCHAR(50),
    country VARCHAR(50),
    city VARCHAR(50),
    state VARCHAR(50),
    postal_code VARCHAR(20),
    region VARCHAR(50),
    product_id VARCHAR(50),
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name VARCHAR(255),
    sales DECIMAL(10,2),
    quantity INT,
    discount DECIMAL(5,2),
    profit DECIMAL(10,2)
);
SET GLOBAL local_infile = 1;
USE sales_analysis;
LOAD DATA LOCAL INFILE 'C:/Users/swapn/Desktop/archive/Sample - Superstore.csv'
INTO TABLE sales
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
DROP TABLE sales;
CREATE TABLE sales (
    row_id VARCHAR(20),
    order_id VARCHAR(50),
    order_date VARCHAR(30),
    ship_date VARCHAR(30),
    ship_mode VARCHAR(50),
    customer_id VARCHAR(50),
    customer_name VARCHAR(100),
    segment VARCHAR(50),
    country VARCHAR(50),
    city VARCHAR(50),
    state VARCHAR(50),
    postal_code VARCHAR(20),
    region VARCHAR(50),
    product_id VARCHAR(50),
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name VARCHAR(255),
    sales VARCHAR(30),
    quantity VARCHAR(20),
    discount VARCHAR(20),
    profit VARCHAR(30)
);
SELECT COUNT(*) AS total_rows
FROM sales;
SELECT *
FROM sales
LIMIT 10;
/* Purpose:

Verify dataset
Understand columns
Check values

You should see:

customer names
product names
sales
profit
region etc.*/
DESCRIBE sales;
-- Display structure of sales table

-- Retrieve all products from Technology category
SELECT *
FROM sales
WHERE region = 'West';
-- Retrieve all orders from West region
SELECT *
FROM sales
WHERE category = 'Technology';

-- Retrieve orders where sales amount is greater than 500
SELECT *
FROM sales
WHERE CAST(sales AS DECIMAL(10,2)) > 500;

-- Retrieve orders placed in year 2017
SELECT *
FROM sales
WHERE order_date LIKE '%2017';

-- Calculate total sales generated by each region
SELECT
    region,
    SUM(CAST(sales AS DECIMAL(10,2))) AS total_sales
FROM sales
GROUP BY region;

-- Calculate average profit for each category
SELECT
    category,
    AVG(CAST(profit AS DECIMAL(10,2))) AS avg_profit
FROM sales
GROUP BY category;

-- Calculate total quantity sold for each category
SELECT
    category,
    SUM(CAST(quantity AS SIGNED)) AS total_quantity
FROM sales
GROUP BY category;

-- Retrieve top 10 products with highest sales

SELECT
    product_name,
    SUM(CAST(sales AS DECIMAL(10,2))) AS total_sales
FROM sales
GROUP BY product_name
ORDER BY total_sales DESC
LIMIT 10;
-- Calculate total profit generated by each category
SELECT
    category,
    SUM(CAST(profit AS DECIMAL(10,2))) AS total_profit
FROM sales
GROUP BY category
ORDER BY total_profit DESC;

-- Analyze yearly sales trend
SELECT
    RIGHT(order_date,4) AS year,
    SUM(CAST(sales AS DECIMAL(10,2))) AS yearly_sales
FROM sales
GROUP BY year
ORDER BY year;

-- Retrieve top 10 customers based on total spending

SELECT
    customer_name,
    SUM(CAST(sales AS DECIMAL(10,2))) AS total_spent
FROM sales
GROUP BY customer_name
ORDER BY total_spent DESC
LIMIT 10;

-- Retrieve products generating highest profit

SELECT
    product_name,
    SUM(CAST(profit AS DECIMAL(10,2))) AS total_profit
FROM sales
GROUP BY product_name
ORDER BY total_profit DESC
LIMIT 10;

-- Retrieve products generating losses

SELECT
    product_name,
    SUM(CAST(profit AS DECIMAL(10,2))) AS total_profit
FROM sales
GROUP BY product_name
HAVING total_profit < 0
ORDER BY total_profit;

-- Check duplicate order and product combinations

SELECT
    order_id,
    product_id,
    COUNT(*) AS duplicate_count
FROM sales
GROUP BY order_id, product_id
HAVING COUNT(*) > 1;

-- Check missing values in important columns
SELECT
    COUNT(*) - COUNT(order_id) AS missing_order_id,
    COUNT(*) - COUNT(customer_id) AS missing_customer_id,
    COUNT(*) - COUNT(sales) AS missing_sales
FROM sales;

-- Retrieve records with invalid quantity values
SELECT *
FROM sales
WHERE CAST(quantity AS SIGNED) <= 0;
